version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13 #
    working_directory: /go/src/github.com/yspro/httpbasicauth
    steps:
      - checkout
      - run: make test
      - codecov/upload:
          file: /go/src/github.com/yspro/httpbasicauth/c.out
          flags: unittests
